# Generated by Django 2.1 on 2018-11-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30)),
                ('data', models.DateTimeField(blank=True)),
                ('imagem', models.CharField(blank=True, max_length=30)),
                ('conteudo', models.CharField(blank=True, max_length=30)),
                ('mentor', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='monitoria',
            name='tag',
            field=models.ManyToManyField(to='monitoria.Tag'),
        ),
    ]
