# Generated by Django 2.1 on 2018-10-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('conteudo', models.CharField(blank=True, max_length=100)),
                ('imagem', models.CharField(blank=True, max_length=100)),
                ('data', models.CharField(blank=True, max_length=100)),
                ('hora', models.CharField(blank=True, max_length=100)),
                ('tag', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
