# Generated by Django 2.1 on 2018-10-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoria',
            name='data',
        ),
        migrations.RemoveField(
            model_name='monitoria',
            name='hora',
        ),
        migrations.AddField(
            model_name='monitoria',
            name='dataHora',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='monitoria',
            name='mentor',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='monitoria',
            name='mentorado',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='monitoria',
            name='conteudo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='monitoria',
            name='nome',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='monitoria',
            name='tag',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
