# Generated by Django 2.1 on 2018-11-23 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('monitoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoria',
            name='mentor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='usuario.Profile'),
        ),
        migrations.AddField(
            model_name='monitoria',
            name='mentored',
            field=models.ManyToManyField(to='usuario.Profile'),
        ),
        migrations.AddField(
            model_name='monitoria',
            name='tag',
            field=models.ManyToManyField(to='monitoria.Tag'),
        ),
    ]
