# Generated by Django 2.1 on 2018-11-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoria', '0002_auto_20181123_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoria',
            name='image',
            field=models.ImageField(blank=True, max_length=30, upload_to=''),
        ),
    ]
